package com.wineguesser.deductive.repository

object DatabaseContract {
    const val DB_EMAIL_VERIFICATION = "verificationEmailSent"

    const val DB_REFERENCE_RED_VARIETY_DESCRIPTORS = "/redVarietyDescriptors"
    const val DB_REFERENCE_WHITE_VARIETY_DESCRIPTORS = "/whiteVarietyDescriptors"
    const val DB_REFERENCE_RED_VARIETAL_DATA = "/redVarietyData"
    const val DB_REFERENCE_WHITE_VARIETAL_DATA = "/whiteVarietyData"

    const val CLARITY_PREPEND = "clarity"
    const val CONCENTRATION_PREPEND = "concentration"
    const val COLOR_PREPEND = "color"
    const val SECONDARY_COLOR_PREPEND = "secondaryColor"
    const val RIM_VARIATION_PREPEND = "rimVariation"
    const val STAINING_PREPEND = "staining"
    const val TEARING_PREPEND = "tearing"
    const val GAS_EVIDENCE_PREPEND = "gasEvidence"
    const val INTENSITY_PREPEND = "intensity"
    const val AGE_ASSESSMENT_PREPEND = "ageAssessment"
    const val WOOD_PREPEND = "oak"
    const val SWEETNESS_PREPEND = "sweetness"
    const val PHENOLIC_BITTER_PREPEND = "phenolicBitter"
    const val TANNIN_PREPEND = "tannin"
    const val ACID_PREPEND = "acidity"
    const val ALCOHOL_PREPEND = "alcohol"
    const val BODY_PREPEND = "body"
    const val TEXTURE_PREPEND = "texture"
    const val BALANCE_PREPEND = "balanced"
    const val FINISH_PREPEND = "finish"
    const val COMPLEXITY_PREPEND = "complexity"

    const val FAULT_PREPEND = "fault"
    const val FRUIT_PREPEND = "fruit"
    const val CHARACTER_PREPEND = "character"
    const val NON_FRUIT_PREPEND = "nonFruit"
    const val EARTH_PREPEND = "earth"
    const val MINERAL_PREPEND = "mineral"

    const val CLEAR = "Clear"
    const val HAZY = "Hazy"
    const val TURBID = "Turbid"
    const val PALE = "Pale"
    const val MEDIUM = "Medium"
    const val DEEP = "Deep"
    const val PURPLE = "Purple"
    const val RUBY = "Ruby"
    const val GARNET = "Garnet"
    const val STRAW = "Straw"
    const val YELLOW = "Yellow"
    const val GOLD = "Gold"
    const val ORANGE = "Orange"
    const val BLUE = "Blue"
    const val BROWN = "Brown"
    const val SILVER = "Silver"
    const val GREEN = "Green"
    const val COPPER = "Copper"
    const val YES = "Yes"
    const val NO = "No"
    const val NONE = "None"
    const val LIGHT = "Light"
    const val HEAVY = "Heavy"
    const val DELICATE = "Delicate"
    const val MODERATE = "Moderate"
    const val POWERFUL = "Powerful"
    const val YOUTHFUL = "Youthful"
    const val DEVELOPING = "Developing"
    const val VINOUS = "Vinous"
    const val OLD = "Old"
    const val NEW = "New"
    const val LARGE = "Large"
    const val SMALL = "Small"
    const val FRENCH = "French"
    const val AMERICAN = "American"
    const val BONE_DRY = "BoneDry"
    const val DRY = "Dry"
    const val OFF_DRY = "OffDry"
    const val MEDIUM_SWEET = "MediumSweet"
    const val SWEET = "Sweet"
    const val LUSCIOUSLY_SWEET = "LusciouslySweet"
    const val LOW = "Low"
    const val MEDIUM_MINUS = "MediumMinus"
    const val MEDIUM_PLUS = "MediumPlus"
    const val HIGH = "High"
    const val FULL = "Full"
    const val CREAMY = "Creamy"
    const val ROUND = "Round"
    const val LEAN = "Lean"
    const val SHORT = "Short"
    const val LONG = "Long"
    const val TCA = "TCA"
    const val HYDROGEN_SULFIDE = "HydrogenSulfide"
    const val VOLATILE_ACIDITY = "VolatileAcidity"
    const val ETHYL_ACETATE = "EthylAcetate"
    const val BRETT = "Brett"
    const val OXIDIZATION = "Oxidization"
    const val OTHER = "Other"
    const val RED = "Red"
    const val BLACK = "Black"
    const val CITRUS = "Citrus"
    const val APPLE_PEAR = "ApplePear"
    const val STONE_PIT = "StonePit"
    const val TROPICAL = "Tropical"
    const val MELON = "Melon"
    const val RIPE = "Ripe"
    const val FRESH = "Fresh"
    const val TART = "Tart"
    const val BAKED = "Baked"
    const val STEWED = "Stewed"
    const val DRIED = "Dried"
    const val DESICCATED = "Desiccated"
    const val BRUISED = "Bruised"
    const val JAMMY = "Jammy"
    const val FLORAL = "Floral"
    const val VEGETAL = "Vegetal"
    const val HERBAL = "Herbal"
    const val SPICE = "Spice"
    const val ANIMAL = "Animal"
    const val BARN = "Barn"
    const val PETROL = "Petrol"
    const val FERMENTATION = "Fermentation"
    const val FOREST_FLOOR = "ForestFloor"
    const val COMPOST = "Compost"
    const val MUSHROOMS = "Mushrooms"
    const val POTTING_SOIL = "PottingSoil"
    const val MINERAL = "Mineral"
    const val WET_STONE = "WetStone"
    const val LIMESTONE = "Limestone"
    const val CHALK = "Chalk"
    const val SLATE = "Slate"
    const val FLINT = "Flint"


    const val KEY_CLARITY_CLEAR = CLARITY_PREPEND + CLEAR
    const val KEY_CLARITY_HAZY = CLARITY_PREPEND + HAZY
    const val KEY_CLARITY_TURBID = CLARITY_PREPEND + TURBID
    const val KEY_CONCENTRATION_PALE = CONCENTRATION_PREPEND + PALE
    const val KEY_CONCENTRATION_MEDIUM = CONCENTRATION_PREPEND + MEDIUM
    const val KEY_CONCENTRATION_DEEP = CONCENTRATION_PREPEND + DEEP
    const val KEY_COLOR_PURPLE = COLOR_PREPEND + PURPLE
    const val KEY_COLOR_RUBY = COLOR_PREPEND + RUBY
    const val KEY_COLOR_GARNET = COLOR_PREPEND + GARNET
    const val KEY_COLOR_STRAW = COLOR_PREPEND + STRAW
    const val KEY_COLOR_YELLOW = COLOR_PREPEND + YELLOW
    const val KEY_COLOR_GOLD = COLOR_PREPEND + GOLD
    const val KEY_SECONDARY_COLOR_ORANGE = SECONDARY_COLOR_PREPEND + ORANGE
    const val KEY_SECONDARY_COLOR_BLUE = SECONDARY_COLOR_PREPEND + BLUE
    const val KEY_SECONDARY_COLOR_RUBY = SECONDARY_COLOR_PREPEND + RUBY
    const val KEY_SECONDARY_COLOR_GARNET = SECONDARY_COLOR_PREPEND + GARNET
    const val KEY_SECONDARY_COLOR_BROWN = SECONDARY_COLOR_PREPEND + BROWN
    const val KEY_SECONDARY_COLOR_SILVER = SECONDARY_COLOR_PREPEND + SILVER
    const val KEY_SECONDARY_COLOR_GREEN = SECONDARY_COLOR_PREPEND + GREEN
    const val KEY_SECONDARY_COLOR_COPPER = SECONDARY_COLOR_PREPEND + COPPER
    const val KEY_RIM_VARIATION_YES = RIM_VARIATION_PREPEND + YES
    const val KEY_RIM_VARIATION_NO = RIM_VARIATION_PREPEND + NO
    const val KEY_STAINING_NONE = STAINING_PREPEND + NONE
    const val KEY_STAINING_LIGHT = STAINING_PREPEND + LIGHT
    const val KEY_STAINING_MEDIUM = STAINING_PREPEND + MEDIUM
    const val KEY_STAINING_HEAVY = STAINING_PREPEND + HEAVY
    const val KEY_TEARING_LIGHT = TEARING_PREPEND + LIGHT
    const val KEY_TEARING_MEDIUM = TEARING_PREPEND + MEDIUM
    const val KEY_TEARING_HEAVY = TEARING_PREPEND + HEAVY
    const val KEY_GAS_EVIDENCE_YES = GAS_EVIDENCE_PREPEND + YES
    const val KEY_GAS_EVIDENCE_NO = GAS_EVIDENCE_PREPEND + NO
    const val KEY_INTENSITY_DELICATE = INTENSITY_PREPEND + DELICATE
    const val KEY_INTENSITY_MODERATE = INTENSITY_PREPEND + MODERATE
    const val KEY_INTENSITY_POWERFUL = INTENSITY_PREPEND + POWERFUL
    const val KEY_AGE_ASSESSMENT_YOUTHFUL = AGE_ASSESSMENT_PREPEND + YOUTHFUL
    const val KEY_AGE_ASSESSMENT_DEVELOPING = AGE_ASSESSMENT_PREPEND + DEVELOPING
    const val KEY_AGE_ASSESSMENT_VINOUS = AGE_ASSESSMENT_PREPEND + VINOUS
    const val KEY_WOOD_OLD = WOOD_PREPEND + OLD
    const val KEY_WOOD_NEW = WOOD_PREPEND + NEW
    const val KEY_WOOD_LARGE = WOOD_PREPEND + LARGE
    const val KEY_WOOD_SMALL = WOOD_PREPEND + SMALL
    const val KEY_WOOD_FRENCH = WOOD_PREPEND + FRENCH
    const val KEY_WOOD_AMERICAN = WOOD_PREPEND + AMERICAN
    const val KEY_SWEETNESS_BONE_DRY = SWEETNESS_PREPEND + BONE_DRY
    const val KEY_SWEETNESS_OFF_DRY = SWEETNESS_PREPEND + OFF_DRY
    const val KEY_SWEETNESS_DRY = SWEETNESS_PREPEND + DRY
    const val KEY_SWEETNESS_MEDIUM_SWEET = SWEETNESS_PREPEND + MEDIUM_SWEET
    const val KEY_SWEETNESS_SWEET = SWEETNESS_PREPEND + SWEET
    const val KEY_SWEETNESS_LUSCIOUSLY_SWEET = SWEETNESS_PREPEND + LUSCIOUSLY_SWEET
    const val KEY_PHENOLIC_BITTER_YES = PHENOLIC_BITTER_PREPEND + YES
    const val KEY_PHENOLIC_BITTER_NO = PHENOLIC_BITTER_PREPEND + NO
    const val KEY_TANNIN_LOW = TANNIN_PREPEND + LOW
    const val KEY_TANNIN_MEDIUM_MINUS = TANNIN_PREPEND + MEDIUM_MINUS
    const val KEY_TANNIN_MEDIUM = TANNIN_PREPEND + MEDIUM
    const val KEY_TANNIN_MEDIUM_PLUS = TANNIN_PREPEND + MEDIUM_PLUS
    const val KEY_TANNIN_HIGH = TANNIN_PREPEND + HIGH
    const val KEY_ACID_LOW = ACID_PREPEND + LOW
    const val KEY_ACID_MEDIUM_MINUS = ACID_PREPEND + MEDIUM_MINUS
    const val KEY_ACID_MEDIUM = ACID_PREPEND + MEDIUM
    const val KEY_ACID_MEDIUM_PLUS = ACID_PREPEND + MEDIUM_PLUS
    const val KEY_ACID_HIGH = ACID_PREPEND + HIGH
    const val KEY_ALCOHOL_LOW = ALCOHOL_PREPEND + LOW
    const val KEY_ALCOHOL_MEDIUM_MINUS = ALCOHOL_PREPEND + MEDIUM_MINUS
    const val KEY_ALCOHOL_MEDIUM = ALCOHOL_PREPEND + MEDIUM
    const val KEY_ALCOHOL_MEDIUM_PLUS = ALCOHOL_PREPEND + MEDIUM_PLUS
    const val KEY_ALCOHOL_HIGH = ALCOHOL_PREPEND + HIGH
    const val KEY_BODY_LIGHT = BODY_PREPEND + LIGHT
    const val KEY_BODY_MEDIUM = BODY_PREPEND + MEDIUM
    const val KEY_BODY_FULL = BODY_PREPEND + FULL
    const val KEY_TEXTURE_CREAMY = TEXTURE_PREPEND + CREAMY
    const val KEY_TEXTURE_ROUND = TEXTURE_PREPEND + ROUND
    const val KEY_TEXTURE_LEAN = TEXTURE_PREPEND + LEAN
    const val KEY_BALANCED_YES = BALANCE_PREPEND + YES
    const val KEY_BALANCED_NO = BALANCE_PREPEND + NO
    const val KEY_FINISH_SHORT = FINISH_PREPEND + SHORT
    const val KEY_FINISH_MEDIUM_MINUS = FINISH_PREPEND + MEDIUM_MINUS
    const val KEY_FINISH_MEDIUM = FINISH_PREPEND + MEDIUM
    const val KEY_FINISH_MEDIUM_PLUS = FINISH_PREPEND + MEDIUM_PLUS
    const val KEY_FINISH_LONG = FINISH_PREPEND + LONG
    const val KEY_COMPLEXITY_LOW = COMPLEXITY_PREPEND + LOW
    const val KEY_COMPLEXITY_MEDIUM_MINUS = COMPLEXITY_PREPEND + MEDIUM_MINUS
    const val KEY_COMPLEXITY_MEDIUM = COMPLEXITY_PREPEND + MEDIUM
    const val KEY_COMPLEXITY_MEDIUM_PLUS = COMPLEXITY_PREPEND + MEDIUM_PLUS
    const val KEY_COMPLEXITY_HIGH = COMPLEXITY_PREPEND + HIGH


    const val KEY_FAULT_TCA = FAULT_PREPEND + TCA
    const val KEY_FAULT_HYDROGEN_SULFIDE = FAULT_PREPEND + HYDROGEN_SULFIDE
    const val KEY_FAULT_VOLATILE_ACIDITY = FAULT_PREPEND + VOLATILE_ACIDITY
    const val KEY_FAULT_ETHYL_ACETATE = FAULT_PREPEND + ETHYL_ACETATE
    const val KEY_FAULT_BRETT = FAULT_PREPEND + BRETT
    const val KEY_FAULT_OXIDIZATION = FAULT_PREPEND + OXIDIZATION
    const val KEY_FAULT_OTHER = FAULT_PREPEND + OTHER
    const val KEY_FRUIT_RED = FRUIT_PREPEND + RED
    const val KEY_FRUIT_BLACK = FRUIT_PREPEND + BLACK
    const val KEY_FRUIT_BLUE = FRUIT_PREPEND + BLUE
    const val KEY_FRUIT_CITRUS = FRUIT_PREPEND + CITRUS
    const val KEY_FRUIT_APPLE_PEAR = FRUIT_PREPEND + APPLE_PEAR
    const val KEY_FRUIT_STONE_PIT = FRUIT_PREPEND + STONE_PIT
    const val KEY_FRUIT_TROPICAL = FRUIT_PREPEND + TROPICAL
    const val KEY_FRUIT_MELON = FRUIT_PREPEND + MELON
    const val KEY_FRUIT_CHARACTER_RIPE = CHARACTER_PREPEND + RIPE
    const val KEY_FRUIT_CHARACTER_FRESH = CHARACTER_PREPEND + FRESH
    const val KEY_FRUIT_CHARACTER_TART = CHARACTER_PREPEND + TART
    const val KEY_FRUIT_CHARACTER_BAKED = CHARACTER_PREPEND + BAKED
    const val KEY_FRUIT_CHARACTER_STEWED = CHARACTER_PREPEND + STEWED
    const val KEY_FRUIT_CHARACTER_DRIED = CHARACTER_PREPEND + DRIED
    const val KEY_FRUIT_CHARACTER_DESICCATED = CHARACTER_PREPEND + DESICCATED
    const val KEY_FRUIT_CHARACTER_BRUISED = CHARACTER_PREPEND + BRUISED
    const val KEY_FRUIT_CHARACTER_JAMMY = CHARACTER_PREPEND + JAMMY
    const val KEY_NON_FRUIT_FLORAL = NON_FRUIT_PREPEND + FLORAL
    const val KEY_NON_FRUIT_VEGETAL = NON_FRUIT_PREPEND + VEGETAL
    const val KEY_NON_FRUIT_HERBAL = NON_FRUIT_PREPEND + HERBAL
    const val KEY_NON_FRUIT_SPICE = NON_FRUIT_PREPEND + SPICE
    const val KEY_NON_FRUIT_ANIMAL = NON_FRUIT_PREPEND + ANIMAL
    const val KEY_NON_FRUIT_BARN = NON_FRUIT_PREPEND + BARN
    const val KEY_NON_FRUIT_PETROL = NON_FRUIT_PREPEND + PETROL
    const val KEY_NON_FRUIT_FERMENTATION = NON_FRUIT_PREPEND + FERMENTATION
    const val KEY_EARTH_FOREST_FLOOR = EARTH_PREPEND + FOREST_FLOOR
    const val KEY_EARTH_COMPOST = EARTH_PREPEND + COMPOST
    const val KEY_EARTH_MUSHROOMS = EARTH_PREPEND + MUSHROOMS
    const val KEY_EARTH_POTTING_SOIL = EARTH_PREPEND + POTTING_SOIL
    const val KEY_MINERAL_MINERAL = MINERAL_PREPEND + MINERAL
    const val KEY_MINERAL_WET_STONE = MINERAL_PREPEND + WET_STONE
    const val KEY_MINERAL_LIMESTONE = MINERAL_PREPEND + LIMESTONE
    const val KEY_MINERAL_CHALK = MINERAL_PREPEND + CHALK
    const val KEY_MINERAL_SLATE = MINERAL_PREPEND + SLATE
    const val KEY_MINERAL_FLINT = MINERAL_PREPEND + FLINT
}
